import { withRlsContext } from "@/lib/db";
import { isAdmin, ForbiddenError } from "@/lib/authorization";
import type {
  CurrentEmployee,
  DocumentCategory,
  DocumentVisibility,
  DocumentDTO,
  DocumentAdminSummaryDTO,
} from "@/types";

export class DocumentNotFoundError extends Error {
  constructor() {
    super("That document isn't available.");
    this.name = "DocumentNotFoundError";
  }
}

export class InvalidDocumentError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "InvalidDocumentError";
  }
}

/**
 * Employee-facing document list. Deliberately just a plain findMany — RLS's document_select
 * policy (prisma/rls.sql) already resolves GLOBAL / DEPARTMENT / INDIVIDUAL assignment and
 * excludes CONFIDENTIAL_HR entirely for a non-admin identity, so there is no visibility logic
 * to re-implement here. Trying to duplicate that filtering in application code would just be
 * a second copy of the rules to keep in sync — the whole point of the RLS layer is that it
 * doesn't need one.
 */
export async function listDocumentsForEmployee(actor: CurrentEmployee): Promise<DocumentDTO[]> {
  const documents = await withRlsContext({ employeeId: actor.id, role: actor.role }, (tx) =>
    tx.document.findMany({
      where: { archivedAt: null },
      include: { acknowledgments: { where: { employeeId: actor.id } } },
      orderBy: [{ category: "asc" }, { title: "asc" }],
    })
  );

  return documents.map((doc) => {
    const currentAck = doc.acknowledgments.find((a) => a.documentVersion === doc.version);
    return {
      id: doc.id,
      title: doc.title,
      category: doc.category as DocumentCategory,
      version: doc.version,
      requiresAcknowledgment: doc.requiresAcknowledgment,
      acknowledgedAt: currentAck ? currentAck.acknowledgedAt.toISOString() : null,
      createdAt: doc.createdAt.toISOString(),
    };
  });
}

/** Employee acknowledges a document — always for themselves, always the CURRENT version. */
export async function acknowledgeDocument(actor: CurrentEmployee, documentId: string) {
  return withRlsContext({ employeeId: actor.id, role: actor.role }, async (tx) => {
    // This read runs under the actor's own RLS identity, so a document they're not allowed
    // to see (wrong assignment, or CONFIDENTIAL_HR) simply doesn't come back — same 404 as a
    // genuinely nonexistent id, never a hint that a hidden document exists.
    const doc = await tx.document.findUnique({ where: { id: documentId } });
    if (!doc || doc.archivedAt) throw new DocumentNotFoundError();
    if (!doc.requiresAcknowledgment) {
      throw new InvalidDocumentError("This document doesn't require acknowledgment.");
    }

    try {
      return await tx.documentAcknowledgment.create({
        data: { documentId, employeeId: actor.id, documentVersion: doc.version },
      });
    } catch (err) {
      // Unique constraint on (documentId, employeeId, documentVersion) — they already
      // acknowledged this exact version. Treat as success: the state they wanted is already
      // true, and a double-click shouldn't surface as an error.
      if (isUniqueConstraintError(err)) {
        const existing = await tx.documentAcknowledgment.findUnique({
          where: {
            documentId_employeeId_documentVersion: {
              documentId,
              employeeId: actor.id,
              documentVersion: doc.version,
            },
          },
        });
        if (existing) return existing;
      }
      throw err;
    }
  });
}

/** Resolves a document for download — the RLS-scoped read here IS the authorization check;
 *  the caller passes doc.storageKey to getSignedDownloadUrl() only after this succeeds. */
export async function getDocumentForDownload(actor: CurrentEmployee, documentId: string) {
  const doc = await withRlsContext({ employeeId: actor.id, role: actor.role }, (tx) =>
    tx.document.findUnique({ where: { id: documentId } })
  );
  if (!doc || doc.archivedAt) throw new DocumentNotFoundError();
  return doc;
}

export interface CreateDocumentInput {
  id: string;
  title: string;
  category: DocumentCategory;
  visibility: DocumentVisibility;
  storageKey: string;
  requiresAcknowledgment: boolean;
  assigneeEmployeeId?: string;
  assigneeDepartmentId?: string;
}

/** Admin uploads a new document. `id` is generated by the caller before the file upload
 *  (see the /api/documents/manage route) so the storage key can be namespaced by document. */
export async function createDocument(actor: CurrentEmployee, input: CreateDocumentInput) {
  if (!isAdmin(actor)) throw new ForbiddenError();
  if (!input.title.trim()) throw new InvalidDocumentError("Title is required.");

  if (input.visibility === "DEPARTMENT" && !input.assigneeDepartmentId) {
    throw new InvalidDocumentError("Choose a department for a department-visible document.");
  }
  if (
    (input.visibility === "INDIVIDUAL" || input.visibility === "CONFIDENTIAL_HR") &&
    !input.assigneeEmployeeId
  ) {
    throw new InvalidDocumentError("Choose an employee for this document.");
  }
  if (input.visibility === "CONFIDENTIAL_HR" && input.requiresAcknowledgment) {
    // Confidential-tier documents are never visible to the employee they're about (see
    // rls.sql) — requiring their acknowledgment would create a checkbox that can never be
    // checked, not a stricter setting.
    throw new InvalidDocumentError(
      "A confidential HR-only document can't require acknowledgment — the employee it's about never sees it."
    );
  }

  return withRlsContext({ employeeId: actor.id, role: actor.role }, (tx) =>
    tx.document.create({
      data: {
        id: input.id,
        title: input.title.trim(),
        category: input.category,
        visibility: input.visibility,
        storageKey: input.storageKey,
        requiresAcknowledgment: input.requiresAcknowledgment,
        assignments:
          input.visibility === "DEPARTMENT"
            ? { create: [{ departmentId: input.assigneeDepartmentId }] }
            : input.visibility === "INDIVIDUAL" || input.visibility === "CONFIDENTIAL_HR"
              ? { create: [{ employeeId: input.assigneeEmployeeId }] }
              : undefined,
      },
    })
  );
}

/**
 * Admin uploads a replacement file for an existing document — the "new version" flow. Bumps
 * `version` and swaps in the new storageKey; the OLD file stays in storage untouched (nothing
 * here deletes it) so a past version is still recoverable if someone needs it. Acknowledgments
 * are per-(document, employee, version) already (see DocumentAcknowledgment's unique
 * constraint), so bumping version alone is what makes every employee's ack stale again —
 * listDocumentsForEmployee only ever matches an ack against doc.version, and
 * listAllDocumentsForAdmin's acknowledgedCount only counts acks at the current version — no
 * separate "clear acknowledgments" step is needed.
 */
export async function createNewDocumentVersion(
  actor: CurrentEmployee,
  documentId: string,
  storageKey: string
) {
  if (!isAdmin(actor)) throw new ForbiddenError();

  return withRlsContext({ employeeId: actor.id, role: actor.role }, async (tx) => {
    const doc = await tx.document.findUnique({ where: { id: documentId } });
    if (!doc) throw new DocumentNotFoundError();
    if (doc.archivedAt) {
      throw new InvalidDocumentError("An archived document can't be given a new version.");
    }

    return tx.document.update({
      where: { id: documentId },
      data: { storageKey, version: { increment: 1 } },
    });
  });
}

/** Admin archives a document — it stops appearing to employees and drops off the active
 *  management list, but is kept (not deleted) for the audit/record-keeping trail. */
export async function archiveDocument(actor: CurrentEmployee, documentId: string) {
  if (!isAdmin(actor)) throw new ForbiddenError();

  return withRlsContext({ employeeId: actor.id, role: actor.role }, async (tx) => {
    const doc = await tx.document.findUnique({ where: { id: documentId } });
    if (!doc) throw new DocumentNotFoundError();
    return tx.document.update({ where: { id: documentId }, data: { archivedAt: new Date() } });
  });
}

/** Admin management list — every document (active and archived), with who it's assigned to
 *  and, for documents that require it, an acknowledgment progress count. */
export async function listAllDocumentsForAdmin(
  actor: CurrentEmployee
): Promise<DocumentAdminSummaryDTO[]> {
  if (!isAdmin(actor)) throw new ForbiddenError();

  return withRlsContext({ employeeId: actor.id, role: actor.role }, async (tx) => {
    const documents = await tx.document.findMany({
      include: {
        assignments: {
          include: {
            employee: { select: { firstName: true, lastName: true, preferredName: true } },
            department: { select: { name: true } },
          },
        },
      },
      orderBy: [{ archivedAt: "asc" }, { createdAt: "desc" }],
    });

    const totalActiveEmployees = await tx.employee.count({ where: { deactivatedAt: null } });
    const departmentCountCache = new Map<string, number>();

    const summaries: DocumentAdminSummaryDTO[] = [];
    for (const doc of documents) {
      let assignedToLabel = "Everyone";
      let eligibleCount = totalActiveEmployees;

      if (doc.visibility === "DEPARTMENT") {
        const assignment = doc.assignments.find((a) => a.departmentId);
        assignedToLabel = assignment?.department?.name ?? "—";
        if (assignment?.departmentId) {
          if (!departmentCountCache.has(assignment.departmentId)) {
            departmentCountCache.set(
              assignment.departmentId,
              await tx.employee.count({
                where: { departmentId: assignment.departmentId, deactivatedAt: null },
              })
            );
          }
          eligibleCount = departmentCountCache.get(assignment.departmentId)!;
        } else {
          eligibleCount = 0;
        }
      } else if (doc.visibility === "INDIVIDUAL" || doc.visibility === "CONFIDENTIAL_HR") {
        const assignment = doc.assignments.find((a) => a.employeeId);
        const emp = assignment?.employee;
        assignedToLabel = emp ? `${emp.preferredName || emp.firstName} ${emp.lastName}` : "—";
        eligibleCount = assignment ? 1 : 0;
      }

      // CONFIDENTIAL_HR documents can never require acknowledgment (enforced at creation) and
      // are never visible to the employee they're about, so this count is always 0/N — not
      // shown as a progress bar in the UI, only as an eligibility fact.
      const acknowledgedCount = doc.requiresAcknowledgment
        ? await tx.documentAcknowledgment.count({
            where: { documentId: doc.id, documentVersion: doc.version },
          })
        : 0;

      summaries.push({
        id: doc.id,
        title: doc.title,
        category: doc.category as DocumentCategory,
        visibility: doc.visibility as DocumentVisibility,
        version: doc.version,
        requiresAcknowledgment: doc.requiresAcknowledgment,
        archivedAt: doc.archivedAt ? doc.archivedAt.toISOString() : null,
        createdAt: doc.createdAt.toISOString(),
        assignedToLabel,
        acknowledgedCount,
        eligibleCount,
      });
    }
    return summaries;
  });
}

function isUniqueConstraintError(err: unknown): boolean {
  return typeof err === "object" && err !== null && "code" in err && err.code === "P2002";
}
